services:
    postgres:
        build: .
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4:5.2
        ports:
            - "80:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@example.com
            - PGADMIN_DEFAULT_PASSWORD=root